### ISSUE TITLE
Automato estado q1

### ISSUE THREAD

**Issue by allangf** [cstipkovic/mini-compiler-cs-mackenzie#4]
@cstipkovic o automato sai do estado q1 e vai para o estado 68 ficando em looping no estado caso hajam mais letras [A-z], porem não poderia fazer isso no estado q1?

**Comment by cstipkovic** [comment]
@allangf, não, pq o estado q1 é o estado de entrada, ele vai pro q68 quando le a primeira letra, ai sim fica no q68 até ler um espaço!
