### ISSUE TITLE
Automato q93

### ISSUE THREAD

**Issue by allangf** [cstipkovic/mini-compiler-cs-mackenzie#7]
@cstipkovic após entrar no estado q93 eu só posso sair se encontrar algo diferente de um * após /* ?
EX:
/**/ inválido
/* */ válido
/*x*/ válido
/* x */ válido
/*1*/ válido
/* 1 */ válido

**Comment by cstipkovic** [comment]
@allangf, do q62 vc vai para q63 se encontrar um espaço e pra q93 se encontrar *, se não for nenhum desses da erro lexico.
Os exemplos que vc colocou acima estão todos invertidos. os que estão como validos, no nosso automato são invalidos.
E do q93 pro q94, obrigatoriamente ele deve ler um texto ou numero, se não, é erro lexico tb.
