### ISSUE TITLE
Revisão Geral do Automato

### ISSUE THREAD

**Issue by allangf** [cstipkovic/mini-compiler-cs-mackenzie#8]
@cstipkovic percebi que em todos os finais de estado tenho um caracter de espaço, isso está correto?

**Comment by cstipkovic** [comment]
@allangf, como eu tinha dito ontem, coloquei o espaço em branco pois foi o que ele pediu no semestre passado, para ter isso depois de cada token lido, mas temos que conversar com ele sobre isso, se vai ter mesmo ou se vamos esperar algo diferente depois de alguns tokens.
