### ISSUE TITLE
Segmentation Fault dentro da main na linha 724

### ISSUE THREAD

**Issue by cstipkovic** [cstipkovic/mini-compiler-cs-mackenzie#9]
Essa é a msg do debug dizendo que falta algum free no malloc que existe:

==44951== Memcheck, a memory error detector
==44951== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==44951== Using Valgrind-3.14.0.GIT and LibVEX; rerun with -h for copyright info
==44951== Command: ./main --leak-check=full
==44951==
==44951== Invalid read of size 1
==44951==    at 0x1000AFD2C: strlen (in /usr/local/Cellar/valgrind/HEAD-26e21fe/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==44951==    by 0x10032BF2E: __strcat_chk (in /usr/lib/system/libsystem_c.dylib)
==44951==    by 0x100002DC7: main (main.c:725)
==44951==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==44951==
==44951==
==44951== Process terminating with default action of signal 11 (SIGSEGV)
==44951==  Access not within mapped region at address 0x0
==44951==    at 0x1000AFD2C: strlen (in /usr/local/Cellar/valgrind/HEAD-26e21fe/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==44951==    by 0x10032BF2E: __strcat_chk (in /usr/lib/system/libsystem_c.dylib)
==44951==    by 0x100002DC7: main (main.c:725)
==44951==  If you believe this happened as a result of a stack
==44951==  overflow in your program's main thread (unlikely but
==44951==  possible), you can try to increase the size of the
==44951==  main thread stack using the --main-stacksize= flag.
==44951==  The main thread stack size used in this run was 8388608.
==44951==
==44951== HEAP SUMMARY:
==44951==     in use at exit: 18,270 bytes in 162 blocks
==44951==   total heap usage: 184 allocs, 22 frees, 92,254 bytes allocated
==44951==
==44951== LEAK SUMMARY:
==44951==    definitely lost: 408 bytes in 8 blocks
==44951==    indirectly lost: 6,864 bytes in 7 blocks
==44951==      possibly lost: 72 bytes in 3 blocks
==44951==    still reachable: 32 bytes in 1 blocks
==44951==         suppressed: 10,894 bytes in 143 blocks
==44951== Rerun with --leak-check=full to see details of leaked memory
==44951==
==44951== For counts of detected and suppressed errors, rerun with: -v
==44951== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 4 from 4)
Segmentation fault: 11

Alguem pode dar uma olhada, por favor?

**Comment by allangf** [comment]
Para que não haja a necessidade de passar o caminho absoluto do arquivo de entrada o ideal é que este esteja no mesmo diretório do exe (solução mais rápida para a leitura), o que causa a segmentação é a linha onde se verificar valor do token.value, já comentei a linha, pois nesse momento não é necessaria.

**Comment by cstipkovic** [comment]
Comentamos a parte do código que estava apresentando o seg fault.
